[chez] Add a failing test for Bytes.toHexString
This demonstrates one of the errors I'm seeing when I try to test out my crypto hashing stuff.
```
Exception: multiple definitions for builtin-Bytes.fromList in body (top-level-program (import (chezscheme) (unison core) (unison cont) (unison boot) (unison primops) ...) (define ref-4n0fgs00 (lambda (...) (...))) (define ref-b589mbg4 (lambda (...) (...))) (define-unison (builtin-Any.Any x0) (list 0 x0)) (define-unison (builtin-Boolean.not x0) (record-case x0 (...) (...))) ...) at line 1, char 1 of test-2.ss
```

`builtin-generated.ss` also exports a Bytes.fromList, which conflicts.