eliminate some view operations because:
java.lang.UnsupportedOperationException: TraversableView.Builder.result
	at scala.collection.TraversableView$NoBuilder.result(TraversableView.scala:27)
	at scala.collection.TraversableView$NoBuilder.result(TraversableView.scala:24)
	at scala.collection.IndexedSeqOptimized.zip(IndexedSeqOptimized.scala:90)
	at scala.collection.IndexedSeqOptimized.zip$(IndexedSeqOptimized.scala:80)
	at scala.collection.mutable.IndexedSeqView$AbstractTransformed.zip(IndexedSeqView.scala:46)
	at org.unisonweb.BuiltinTypes$.org$unisonweb$BuiltinTypes$$$anonfun$dataConstructorish$4(BuiltinTypes.scala:126)